#!/usr/bin/env bash
#
# certify.sh - shared qualification runner
#
# Invoked by per-target wrapper scripts generated by the flake.  The wrapper
# exports TARGET_* env vars describing the simulator target, then execs this
# script.  This script dispatches on $TARGET_ADAPTER to run the test suite
# and produce a standard set of qualification artefacts.
#
# Required env vars (all targets):
#   TARGET_NAME          registry key (e.g. quartus-25.1-sim-only-qrun)
#   TARGET_ADAPTER       "container" | "native" | "fhs"
#   TARGET_DISPLAY_NAME  human-readable
#   TARGET_TOOL          simulator tool name (qrun|modelsim|verilator|xsim)
#   TARGET_PYTEST_FILTER pytest -k expression
#   TOOL_GROUP, TOOL_VERSION, QUALIFIED_VERSION  qualification identifiers
#   ARTEFACTS_ROOT       parent dir to write run-id subdir into
#   CERT_TOOLS_DIR       path to qualification-helpers.sh host dir
#   TIMING_SUMMARY_SCRIPT  nix store path to timing-summary.py
#
# Container adapter extras:
#   TARGET_IMAGE, TARGET_INSTALL_ROOT, TARGET_CONTAINER_PATH,
#   TARGET_EXPECTED_QUARTUS ("" to skip), TARGET_EXPECTED_QUESTA,
#   TARGET_HAS_QUARTUS_SH (0|1), LICENSE_DIR, CONTAINER_RUNTIME
#
# Native adapter extras:
#   TARGET_EXPECTED_VERILATOR, TARGET_VERILATOR_STORE_PATH
#
# FHS adapter extras:
#   TARGET_EXPECTED_VIVADO, TARGET_VIVADO_PROFILE,
#   TARGET_VIVADO_STORE_PATH, TARGET_VIVADO_IS_STUB, TARGET_QUALIFIED_ROOT

set -euo pipefail

# shellcheck source=/dev/null
source "${CERT_TOOLS_DIR}/scripts/qualification-helpers.sh"

OUTPUT_DIR=""
PYTEST_FILTER_OVERRIDE=""
REUSE_BUILD=0
SIM_DEBUG_LEVEL=""
SIM_RUNTIME_STATS=0
XSIM_RUN_MODE=""
REPO_ROOT="${REPO_ROOT:-$(pwd)}"

usage() {
  cat <<EOF
Usage: svunit-certify-${TARGET_NAME} [--output-dir DIR] [--filter EXPR] [--reuse-build] [--xsim-reuse-build] [--sim-debug-level LEVEL] [--sim-runtime-stats] [--xsim-run-mode MODE]

Target:  ${TARGET_NAME}
Adapter: ${TARGET_ADAPTER}
Display: ${TARGET_DISPLAY_NAME}

Options:
  --output-dir DIR       Override artefact output dir (default: per qualification standard)
  --filter EXPR          Override pytest -k filter (default: ${TARGET_PYTEST_FILTER})
  --reuse-build          Experimental qrun/modelsim/xsim mode; reuse unchanged build artefacts
  --xsim-reuse-build     Backward-compatible xsim-only alias for --reuse-build
  --sim-debug-level LVL  Forward normalized debug level to runSVUnit
  --sim-runtime-stats    Forward normalized runtime-statistics request to runSVUnit
  --xsim-run-mode MODE   Forward xsim run mode to runSVUnit (separate or standalone)
EOF
  exit 2
}

while [ $# -gt 0 ]; do
  case "$1" in
    --output-dir|-o) OUTPUT_DIR="$2"; shift 2 ;;
    --filter|-k)     PYTEST_FILTER_OVERRIDE="$2"; shift 2 ;;
    --reuse-build) REUSE_BUILD=1; shift ;;
    --sim-debug-level)
      SIM_DEBUG_LEVEL="$2"
      shift 2
      ;;
    --xsim-reuse-build)
      if [ "${TARGET_TOOL}" != "xsim" ]; then
        echo "ERROR: --xsim-reuse-build is only supported for xsim targets." >&2
        exit 2
      fi
      REUSE_BUILD=1
      shift
      ;;
    --sim-runtime-stats) SIM_RUNTIME_STATS=1; shift ;;
    --xsim-run-mode)
      XSIM_RUN_MODE="$2"
      shift 2
      ;;
    --help|-h)       usage ;;
    *) echo "Unknown argument: $1" >&2; usage ;;
  esac
done

PYTEST_FILTER="${PYTEST_FILTER_OVERRIDE:-${TARGET_PYTEST_FILTER}}"
PER_FIXTURE_PYTEST_FILTER="(${PYTEST_FILTER}) and not profile_compile_once"
COMPILE_ONCE_PYTEST_FILTER="(${PYTEST_FILTER}) and profile_compile_once"
SIM_DEBUG_LEVEL="${SIM_DEBUG_LEVEL,,}"
XSIM_RUN_MODE="${XSIM_RUN_MODE,,}"

if [ "${REUSE_BUILD}" = "1" ] &&
   [ "${TARGET_TOOL}" != "qrun" ] &&
   [ "${TARGET_TOOL}" != "modelsim" ] &&
   [ "${TARGET_TOOL}" != "xsim" ]; then
  echo "ERROR: --reuse-build is only supported for qrun, modelsim, and xsim targets." >&2
  exit 2
fi

case "${SIM_DEBUG_LEVEL}" in
  ""|none|low|medium|med|high|all) ;;
  *)
    echo "ERROR: --sim-debug-level must be one of none, low, medium, med, high, or all." >&2
    exit 2
    ;;
esac

case "${XSIM_RUN_MODE}" in
  ""|separate|standalone) ;;
  *)
    echo "ERROR: --xsim-run-mode must be one of separate or standalone." >&2
    exit 2
    ;;
esac

if [ "${XSIM_RUN_MODE}" = "standalone" ] && [ "${TARGET_TOOL}" != "xsim" ]; then
  echo "ERROR: --xsim-run-mode standalone is only supported for xsim targets." >&2
  exit 2
fi

setup_tool_timing_wrappers() {
  local timing_dir="$1"
  shift

  local wrapper_bin="${timing_dir}/bin"
  local timing_log="${timing_dir}/tool-invocations.tsv"
  mkdir -p "${wrapper_bin}"
  printf 'start_utc\ttool\tduration_ms\texit_code\tcwd\targs\tprofile_mode\tend_utc\tstart_epoch_ms\tend_epoch_ms\tpid\n' > "${timing_log}"

  local tool real_tool wrapper
  for tool in "$@"; do
    real_tool="$(command -v "$tool" 2>/dev/null || true)"
    if [ -z "${real_tool}" ]; then
      continue
    fi
    wrapper="${wrapper_bin}/${tool}"
    {
      printf '#!/usr/bin/env bash\n'
      printf 'set -uo pipefail\n'
      printf 'real_tool=%q\n' "${real_tool}"
      printf 'tool_name=%q\n' "${tool}"
      printf 'timing_log=%q\n' "${timing_log}"
      cat <<'WRAP_EOF'
start_utc="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
start_ns="$(date +%s%N)"
start_epoch_ms=$(( start_ns / 1000000 ))
pid="${BASHPID:-$$}"
"${real_tool}" "$@"
rc=$?
end_utc="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
end_ns="$(date +%s%N)"
end_epoch_ms=$(( end_ns / 1000000 ))
duration_ms=$(( (end_ns - start_ns) / 1000000 ))
args=()
for arg in "$@"; do
  args+=("$(printf '%q' "$arg")")
done
printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
  "$start_utc" "$tool_name" "$duration_ms" "$rc" "$PWD" "${args[*]}" \
  "${SVUNIT_PROFILE_MODE:-unknown}" "$end_utc" "$start_epoch_ms" \
  "$end_epoch_ms" "$pid" \
  >> "$timing_log"
exit "$rc"
WRAP_EOF
    } > "${wrapper}"
    chmod +x "${wrapper}"
  done

  export PATH="${wrapper_bin}:${PATH}"
}

write_tool_timing_summary() {
  local timing_dir="$1"
  local timing_log="${timing_dir}/tool-invocations.tsv"

  [ -f "${timing_log}" ] || return 0

  awk -F '\t' '
    BEGIN {
      OFS = "\t"
      print "profile_mode", "tool", "count", "total_ms", "avg_ms", "max_ms"
    }
    NR > 1 {
      duration_ms = $3 + 0
      key = $7 SUBSEP $2
      if (!(key in seen)) {
        seen[key] = 1
        keys[++n] = key
        profile_mode[key] = $7
        tool[key] = $2
      }
      count[key] += 1
      total_ms[key] += duration_ms
      if (duration_ms > max_ms[key]) {
        max_ms[key] = duration_ms
      }
    }
    END {
      for (i = 1; i <= n; i++) {
        key = keys[i]
        avg_ms = count[key] ? total_ms[key] / count[key] : 0
        printf "%s\t%s\t%d\t%.0f\t%.1f\t%.0f\n",
          profile_mode[key], tool[key], count[key], total_ms[key], avg_ms, max_ms[key]
      }
    }
  ' "${timing_log}" > "${timing_dir}/tool-summary.tsv"

  awk -F '\t' '
    BEGIN {
      OFS = "\t"
      print "profile_mode", "cwd", "tool", "count", "total_ms", "avg_ms", "max_ms"
    }
    NR > 1 {
      duration_ms = $3 + 0
      key = $7 SUBSEP $5 SUBSEP $2
      if (!(key in seen)) {
        seen[key] = 1
        keys[++n] = key
        profile_mode[key] = $7
        cwd[key] = $5
        tool[key] = $2
      }
      count[key] += 1
      total_ms[key] += duration_ms
      if (duration_ms > max_ms[key]) {
        max_ms[key] = duration_ms
      }
    }
    END {
      for (i = 1; i <= n; i++) {
        key = keys[i]
        avg_ms = count[key] ? total_ms[key] / count[key] : 0
        printf "%s\t%s\t%s\t%d\t%.0f\t%.1f\t%.0f\n",
          profile_mode[key], cwd[key], tool[key], count[key], total_ms[key], avg_ms, max_ms[key]
      }
    }
  ' "${timing_log}" > "${timing_dir}/tool-by-cwd.tsv"

  echo "Wrote tool timing summaries in ${timing_dir}"
}

run_profile_pytest() {
  local mode="$1"
  local filter="$2"
  local xml="$3"
  local start_utc start_ns end_utc end_ns duration_ms pytest_rc

  echo ""
  start_utc="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  start_ns="$(date +%s%N)"
  echo "--- pytest ${mode} -k ${filter} start=${start_utc} ---"
  set +e
  SVUNIT_PROFILE_MODE="${mode}" \
    SVUNIT_REUSE_BUILD="${REUSE_BUILD}" \
    SVUNIT_XSIM_REUSE_BUILD="$([ "${TARGET_TOOL}" = "xsim" ] && echo "${REUSE_BUILD}" || echo 0)" \
    SVUNIT_SIM_DEBUG_LEVEL="${SIM_DEBUG_LEVEL}" \
    SVUNIT_SIM_RUNTIME_STATS="${SIM_RUNTIME_STATS}" \
    SVUNIT_XSIM_RUN_MODE="${XSIM_RUN_MODE}" \
    python3 -m pytest -v -k "${filter}" \
    --tb=short \
    --basetemp="${OUTPUT_DIR}/pytest-${mode}" \
    --durations=0 \
    --junitxml="${xml}" \
    2>&1
  pytest_rc=$?
  set -e
  end_utc="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  end_ns="$(date +%s%N)"
  duration_ms=$(( (end_ns - start_ns) / 1000000 ))
  echo "--- pytest ${mode} end=${end_utc} duration_ms=${duration_ms} exit_code=${pytest_rc} ---"
}

write_sim_runtime_stats_summary() {
  local output_dir="$1"
  local log="${output_dir}/test-log.txt"
  local tsv="${output_dir}/sim-runtime-stats.tsv"
  local json="${output_dir}/sim-runtime-stats.json"

  [ -f "${log}" ] || return 0

  SVUNIT_CERTIFY_SIM_RUNTIME_STATS="${SIM_RUNTIME_STATS:-0}" \
    python3 - "${output_dir}" "${log}" "${tsv}" "${json}" <<'PY'
import glob
import json
import os
import re
import sys

output_dir, log_path, tsv_path, json_path = sys.argv[1:5]
mode = "unknown"
entries = []
seen_sources = set()
runtime_stats_enabled = os.environ.get("SVUNIT_CERTIFY_SIM_RUNTIME_STATS") == "1"

mode_start_re = re.compile(r"^--- pytest ([^ ]+) .* start=")
xsim_re = re.compile(
    r"xsimkernel Simulation Memory Usage:\s+(\d+)\s+KB "
    r"\(Peak:\s+(\d+)\s+KB\), Simulation CPU Usage:\s+(\d+)\s+ms"
)
questa_stats_arg_re = re.compile(r"(?:^|\s)-(?:printsimstats|stats(?:=\S+)?)\b", re.I)
questa_tool_re = re.compile(r"^(vlog|vopt|vsim)\b", re.I)
questa_memory_re = re.compile(
    r"mem:\s+(.+?)\s+([0-9]+(?:\.[0-9]+)?)\s+([kmg]b)\b",
    re.I,
)
questa_time_re = re.compile(
    r"(vopt|elab|sim|total|license):\s+(.+?)\s+"
    r"([0-9]+(?:\.[0-9]+)?)\s+s\b",
    re.I,
)
hdl_time_re = re.compile(r"HDL Simulation time\s+(.+)$", re.I)
end_time_re = re.compile(r"End time:.*Elapsed time:\s+([0-9:]+)", re.I)
verilator_wall_re = re.compile(
    r"^- Verilator:\s+\$finish .*?walltime\s+([0-9]+(?:\.[0-9]+)?)\s+s;",
    re.I,
)
verilator_cpu_re = re.compile(
    r"^- Verilator:\s+cpu\s+([0-9]+(?:\.[0-9]+)?)\s+s on "
    r"([0-9]+)\s+threads; alloced\s+([0-9]+(?:\.[0-9]+)?)\s+([kmg]b)\b",
    re.I,
)


def normalize_label(label):
    label = label.lower()
    label = re.sub(r"\([^)]*\)", "", label)
    label = re.sub(r"[^a-z0-9]+", "_", label)
    return label.strip("_")


def memory_to_kb(value, unit):
    multipliers = {
        "kb": 1,
        "mb": 1024,
        "gb": 1024 * 1024,
    }
    return int(round(float(value) * multipliers[unit.lower()]))


def seconds_to_ms(value):
    return int(round(float(value) * 1000))


def strip_log_prefix(line):
    line = line.rstrip("\n")
    if line.startswith("#"):
        line = line[1:]
    return line.strip()


def source_for_path(path):
    return os.path.relpath(path, output_dir) if path.startswith(output_dir) else path


def add_entry(profile_mode, simulator, phase, current_kb, peak_kb, cpu_ms, source, line_number, **extra):
    key = (source, line_number, simulator, phase)
    if key in seen_sources:
        return
    seen_sources.add(key)
    entry = {
        "profile_mode": profile_mode,
        "simulator": simulator,
        "phase": phase,
        "current_memory_kb": current_kb,
        "peak_memory_kb": peak_kb,
        "simulation_cpu_ms": cpu_ms,
        "source": source,
        "line": line_number,
    }
    entry.update(extra)
    entries.append(entry)


def add_questa_entry(profile_mode, simulator, source, block):
    memory_metrics = block["memory_metrics_kb"]
    time_metrics = block["time_metrics_ms"]
    current_kb = None
    for label in (
        "size_during_sim",
        "size_after_elab",
        "size_of_process",
        "size_of_vopt_process",
    ):
        if label in memory_metrics:
            current_kb = memory_metrics[label]
            break
    if current_kb is None and memory_metrics:
        current_kb = max(memory_metrics.values())

    add_entry(
        profile_mode,
        simulator,
        block["phase"],
        current_kb,
        max(memory_metrics.values()) if memory_metrics else None,
        time_metrics.get("sim_cpu_time"),
        source,
        block["line"],
        simulation_wall_ms=time_metrics.get("sim_wall_time"),
        total_cpu_ms=time_metrics.get("total_cpu_time"),
        total_wall_ms=time_metrics.get("total_wall_time"),
        memory_metrics_kb=memory_metrics,
        time_metrics_ms=time_metrics,
        hdl_simulation_time=block.get("hdl_simulation_time"),
        elapsed_time=block.get("elapsed_time"),
    )


def host_path(path):
    if path.startswith("/artefacts/"):
        return os.path.join(output_dir, path[len("/artefacts/"):])
    if path == "/artefacts":
        return output_dir
    return path


def scan_log(path, profile_mode, simulator):
    try:
        with open(path, "r", errors="replace") as log_file:
            source = source_for_path(path)
            current_questa_tool = None
            questa_block = None
            verilator_block = None
            for line_number, line in enumerate(log_file, 1):
                stripped = strip_log_prefix(line)
                xsim_match = xsim_re.search(line)
                if xsim_match:
                    current_kb, peak_kb, cpu_ms = map(int, xsim_match.groups())
                    add_entry(
                        profile_mode,
                        simulator,
                        "simulation",
                        current_kb,
                        peak_kb,
                        cpu_ms,
                        source,
                        line_number,
                    )

                verilator_wall_match = verilator_wall_re.search(stripped)
                if verilator_wall_match:
                    verilator_block = {
                        "line": line_number,
                        "wall_ms": seconds_to_ms(verilator_wall_match.group(1)),
                    }
                    continue

                verilator_cpu_match = verilator_cpu_re.search(stripped)
                if verilator_cpu_match:
                    cpu_s, threads, memory, unit = verilator_cpu_match.groups()
                    memory_kb = memory_to_kb(memory, unit)
                    add_entry(
                        profile_mode,
                        "verilator",
                        "simulation",
                        memory_kb,
                        memory_kb,
                        seconds_to_ms(cpu_s),
                        source,
                        verilator_block["line"] if verilator_block else line_number,
                        simulation_wall_ms=verilator_block["wall_ms"] if verilator_block else None,
                        total_cpu_ms=seconds_to_ms(cpu_s),
                        total_wall_ms=verilator_block["wall_ms"] if verilator_block else None,
                        verilator_threads=int(threads),
                    )
                    verilator_block = None
                    continue

                tool_match = questa_tool_re.match(stripped)
                if tool_match and questa_stats_arg_re.search(stripped):
                    current_questa_tool = tool_match.group(1).lower()

                if stripped == "Memory Statistics":
                    questa_block = {
                        "phase": current_questa_tool or "unknown",
                        "line": line_number,
                        "memory_metrics_kb": {},
                        "time_metrics_ms": {},
                    }
                    continue

                if questa_block is None:
                    continue

                memory_match = questa_memory_re.search(stripped)
                if memory_match:
                    label, value, unit = memory_match.groups()
                    questa_block["memory_metrics_kb"][normalize_label(label)] = memory_to_kb(value, unit)
                    continue

                time_match = questa_time_re.search(stripped)
                if time_match:
                    section, label, value = time_match.groups()
                    metric = "{}_{}".format(section.lower(), normalize_label(label))
                    questa_block["time_metrics_ms"][metric] = seconds_to_ms(value)
                    continue

                hdl_match = hdl_time_re.search(stripped)
                if hdl_match:
                    questa_block["hdl_simulation_time"] = hdl_match.group(1).strip()
                    continue

                end_match = end_time_re.search(stripped)
                if end_match:
                    questa_block["elapsed_time"] = end_match.group(1)
                    add_questa_entry(profile_mode, simulator, source, questa_block)
                    questa_block = None

            if questa_block is not None:
                add_questa_entry(profile_mode, simulator, source, questa_block)
    except OSError:
        return


with open(log_path, "r", errors="replace") as log:
    for line_number, line in enumerate(log, 1):
        mode_match = mode_start_re.search(line)
        if mode_match:
            mode = mode_match.group(1)
            continue

        xsim_match = xsim_re.search(line)
        if xsim_match:
            current_kb, peak_kb, cpu_ms = map(int, xsim_match.groups())
            add_entry(mode, "xsim", "simulation", current_kb, peak_kb, cpu_ms, "test-log.txt", line_number)

tool_by_cwd = None
for candidate in ("vivado-tool-timing", "tool-timing"):
    path = os.path.join(output_dir, candidate, "tool-by-cwd.tsv")
    if os.path.exists(path):
        tool_by_cwd = path
        break

if tool_by_cwd:
    with open(tool_by_cwd, "r", errors="replace") as timing:
        header = timing.readline()
        for row in timing:
            fields = row.rstrip("\n").split("\t")
            if len(fields) < 3:
                continue
            profile_mode, cwd, tool = fields[:3]
            simulator_by_tool = {
                "xsim": "xsim",
                "vsim": "modelsim",
                "qrun": "qrun",
            }
            if runtime_stats_enabled:
                simulator_by_tool["verilator"] = "verilator"
            if tool not in simulator_by_tool:
                continue
            for run_log in sorted(glob.glob(os.path.join(host_path(cwd), "run*.log"))):
                scan_log(run_log, profile_mode, simulator_by_tool[tool])

summary = {}
for entry in entries:
    key = (entry["profile_mode"], entry["simulator"], entry["phase"])
    current = summary.setdefault(key, {
        "profile_mode": entry["profile_mode"],
        "simulator": entry["simulator"],
        "phase": entry["phase"],
        "count": 0,
        "total_simulation_cpu_ms": 0,
        "total_cpu_ms": 0,
        "total_wall_ms": 0,
        "max_peak_memory_kb": 0,
    })
    current["count"] += 1
    current["total_simulation_cpu_ms"] += entry.get("simulation_cpu_ms") or 0
    current["total_cpu_ms"] += entry.get("total_cpu_ms") or 0
    current["total_wall_ms"] += entry.get("total_wall_ms") or 0
    current["max_peak_memory_kb"] = max(
        current["max_peak_memory_kb"],
        entry.get("peak_memory_kb") or 0,
    )

with open(tsv_path, "w") as tsv:
    tsv.write(
        "profile_mode\tsimulator\tcurrent_memory_kb\tpeak_memory_kb\t"
        "simulation_cpu_ms\tsource\tline\tphase\tsimulation_wall_ms\t"
        "total_cpu_ms\ttotal_wall_ms\n"
    )
    for entry in entries:
        def value(name):
            val = entry.get(name)
            return "" if val is None else str(val)
        tsv.write(
            "{profile_mode}\t{simulator}\t{current_memory_kb}\t"
            "{peak_memory_kb}\t{simulation_cpu_ms}\t{source}\t{line}\t"
            "{phase}\t{simulation_wall_ms}\t{total_cpu_ms}\t{total_wall_ms}\n"
            .format(
                profile_mode=value("profile_mode"),
                simulator=value("simulator"),
                current_memory_kb=value("current_memory_kb"),
                peak_memory_kb=value("peak_memory_kb"),
                simulation_cpu_ms=value("simulation_cpu_ms"),
                source=value("source"),
                line=value("line"),
                phase=value("phase"),
                simulation_wall_ms=value("simulation_wall_ms"),
                total_cpu_ms=value("total_cpu_ms"),
                total_wall_ms=value("total_wall_ms"),
            )
        )

with open(json_path, "w") as jf:
    json.dump({
        "entries": entries,
        "summary": list(summary.values()),
    }, jf, indent=2, sort_keys=True)
    jf.write("\n")
PY

  echo "Wrote sim-runtime-stats.tsv/json ($(awk 'NR > 1 { count += 1 } END { print count + 0 }' "${tsv}") entries)"
}

if [ ! -f "${REPO_ROOT}/Setup.bsh" ]; then
  echo "ERROR: Setup.bsh not found. Run from the SVUnit repo root or set REPO_ROOT." >&2
  exit 2
fi

# ---------------------------------------------------------------------------
# Adapter pre-validation (before we create any artefacts)
# ---------------------------------------------------------------------------
case "${TARGET_ADAPTER}" in
  container)
    for lic in quartus_license.dat questa_license.dat; do
      if [ ! -f "${LICENSE_DIR}/${lic}" ]; then
        echo "ERROR: Missing ${LICENSE_DIR}/${lic}" >&2
        exit 2
      fi
    done
    if ! "${CONTAINER_RUNTIME}" image exists "${TARGET_IMAGE}" >/dev/null 2>&1; then
      echo "ERROR: Container image ${TARGET_IMAGE} not found." >&2
      echo "Build it via the upstream Quartus Pro podman flake first." >&2
      exit 2
    fi
    ;;
  native)
    if ! command -v verilator >/dev/null 2>&1; then
      echo "ERROR: verilator binary not found on PATH." >&2
      exit 2
    fi
    VERILATOR_VERSION_OUT="$(verilator --version 2>&1)"
    if ! printf '%s\n' "${VERILATOR_VERSION_OUT}" | grep -qF "${TARGET_EXPECTED_VERILATOR}"; then
      echo "ERROR: verilator version mismatch - expected ${TARGET_EXPECTED_VERILATOR}, got ${VERILATOR_VERSION_OUT}" >&2
      exit 2
    fi
    for bin in gcc make; do
      if ! command -v "$bin" >/dev/null 2>&1; then
        echo "ERROR: $bin not found on PATH (required for Verilator compilation)." >&2
        exit 2
      fi
    done
    ;;
  fhs)
    if [ "${TARGET_VIVADO_IS_STUB}" != "0" ]; then
      echo "ERROR: Vivado input is marked as a stub; refusing to run ${TARGET_NAME}." >&2
      exit 2
    fi
    for bin in vivado xvlog xvhdl xelab xsim; do
      if ! command -v "$bin" >/dev/null 2>&1; then
        echo "ERROR: $bin not found on PATH (required for Vivado xsim qualification)." >&2
        exit 2
      fi
    done
    ;;
  *)
    echo "ERROR: Unknown adapter ${TARGET_ADAPTER} for target ${TARGET_NAME}." >&2
    exit 2
    ;;
esac

# ---------------------------------------------------------------------------
# Build run ID and prep output directory
# ---------------------------------------------------------------------------
qh_detect_gpu
qh_build_run_id --no-gpu-suffix

OUTPUT_DIR="${OUTPUT_DIR:-${ARTEFACTS_ROOT}/${QH_RUN_ID}}"
mkdir -p "${OUTPUT_DIR}"

SVUNIT_COMMIT="$(git -C "${REPO_ROOT}" rev-parse HEAD 2>/dev/null || echo "unknown")"

IMAGE_ID="N/A"
if [ "${TARGET_ADAPTER}" = "container" ]; then
  IMAGE_ID="$("${CONTAINER_RUNTIME}" image inspect "${TARGET_IMAGE}" --format '{{.Id}}' 2>/dev/null || echo "unknown")"
  "${CONTAINER_RUNTIME}" inspect "${TARGET_IMAGE}" > "${OUTPUT_DIR}/image-inspect.json" 2>/dev/null || true
fi

echo "=== SVUnit Qualification ==="
echo "Tool:       ${TOOL_GROUP} ${QUALIFIED_VERSION}"
echo "Target:     ${TARGET_NAME}"
echo "Display:    ${TARGET_DISPLAY_NAME}"
echo "Run ID:     ${QH_RUN_ID}"
echo "Output:     ${OUTPUT_DIR}"
echo "Filter:     ${PYTEST_FILTER}"
echo "Per-fixture regression: ${PER_FIXTURE_PYTEST_FILTER}"
echo "Compile-once regression: ${COMPILE_ONCE_PYTEST_FILTER}"
echo "reuse build: ${REUSE_BUILD}"
echo "sim debug level: ${SIM_DEBUG_LEVEL:-default}"
echo "sim runtime stats: ${SIM_RUNTIME_STATS}"
echo "xsim run mode: ${XSIM_RUN_MODE:-separate}"
echo ""

# ---------------------------------------------------------------------------
# Run the test suite
# ---------------------------------------------------------------------------
EXIT_CODE=0

case "${TARGET_ADAPTER}" in
  container)
    echo "--- Running qualification inside container ${TARGET_IMAGE} ---"
    # shellcheck disable=SC2016
    container_script="$(cat <<'CONTAINER_EOF'
set -euo pipefail

# --- Bootstrap full Perl runtime (File::Find, IO::Dir, etc) ---
# Some sim-only container variants (e.g. quartus-pro-linux:25.1.1.125-sim-only)
# ship with `perl-base` only, which lacks core modules like File::Find (via
# perl-modules-*) and IO::Dir (via libperl5.38t64) that bin/runSVUnit and
# bin/buildSVUnit require. Installing the `perl` metapackage pulls in both.
# Idempotent - no-ops on images that already have perl full (e.g.
# quartus-pro-linux:23.4.0.79).
if ! perl -MFile::Find -MIO::Dir -e 1 >/dev/null 2>&1; then
  echo "--- bootstrap: installing perl metapackage (missing core/IO modules) ---"
  apt-get update -q >/dev/null 2>&1
  apt-get install -y -q --no-install-recommends perl >/dev/null 2>&1 \
    || { echo "FAIL: could not install perl metapackage" >&2; exit 2; }
  perl -MFile::Find -MIO::Dir -e 1 \
    || { echo "FAIL: File::Find / IO::Dir still unavailable after apt install" >&2; exit 2; }
  echo "OK: perl metapackage installed (File::Find, IO::Dir, etc available)"
fi

# --- Bootstrap pytest ---
python3 -c "
import urllib.request, tempfile, subprocess, sys
f = tempfile.NamedTemporaryFile(suffix='.py', delete=False)
urllib.request.urlretrieve('https://bootstrap.pypa.io/get-pip.py', f.name)
subprocess.check_call([sys.executable, f.name, '--break-system-packages', '-q'])
"
pip3 install --break-system-packages -q "pytest>=7,<9" "pytest-datafiles==2.0" 2>&1

setup_tool_timing_wrappers() {
  local timing_dir="$1"
  shift

  local wrapper_bin="${timing_dir}/bin"
  local timing_log="${timing_dir}/tool-invocations.tsv"
  mkdir -p "${wrapper_bin}"
  printf 'start_utc\ttool\tduration_ms\texit_code\tcwd\targs\tprofile_mode\tend_utc\tstart_epoch_ms\tend_epoch_ms\tpid\n' > "${timing_log}"

  local tool real_tool wrapper
  for tool in "$@"; do
    real_tool="$(command -v "$tool" 2>/dev/null || true)"
    if [ -z "${real_tool}" ]; then
      continue
    fi
    wrapper="${wrapper_bin}/${tool}"
    {
      printf '#!/usr/bin/env bash\n'
      printf 'set -uo pipefail\n'
      printf 'real_tool=%q\n' "${real_tool}"
      printf 'tool_name=%q\n' "${tool}"
      printf 'timing_log=%q\n' "${timing_log}"
      cat <<'WRAP_EOF'
start_utc="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
start_ns="$(date +%s%N)"
start_epoch_ms=$(( start_ns / 1000000 ))
pid="${BASHPID:-$$}"
"${real_tool}" "$@"
rc=$?
end_utc="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
end_ns="$(date +%s%N)"
end_epoch_ms=$(( end_ns / 1000000 ))
duration_ms=$(( (end_ns - start_ns) / 1000000 ))
args=()
for arg in "$@"; do
  args+=("$(printf '%q' "$arg")")
done
printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
  "$start_utc" "$tool_name" "$duration_ms" "$rc" "$PWD" "${args[*]}" \
  "${SVUNIT_PROFILE_MODE:-unknown}" "$end_utc" "$start_epoch_ms" \
  "$end_epoch_ms" "$pid" \
  >> "$timing_log"
exit "$rc"
WRAP_EOF
    } > "${wrapper}"
    chmod +x "${wrapper}"
  done

  export PATH="${wrapper_bin}:${PATH}"
}

write_tool_timing_summary() {
  local timing_dir="$1"
  local timing_log="${timing_dir}/tool-invocations.tsv"

  [ -f "${timing_log}" ] || return 0

  awk -F '\t' '
    BEGIN {
      OFS = "\t"
      print "profile_mode", "tool", "count", "total_ms", "avg_ms", "max_ms"
    }
    NR > 1 {
      duration_ms = $3 + 0
      key = $7 SUBSEP $2
      if (!(key in seen)) {
        seen[key] = 1
        keys[++n] = key
        profile_mode[key] = $7
        tool[key] = $2
      }
      count[key] += 1
      total_ms[key] += duration_ms
      if (duration_ms > max_ms[key]) {
        max_ms[key] = duration_ms
      }
    }
    END {
      for (i = 1; i <= n; i++) {
        key = keys[i]
        avg_ms = count[key] ? total_ms[key] / count[key] : 0
        printf "%s\t%s\t%d\t%.0f\t%.1f\t%.0f\n",
          profile_mode[key], tool[key], count[key], total_ms[key], avg_ms, max_ms[key]
      }
    }
  ' "${timing_log}" > "${timing_dir}/tool-summary.tsv"

  awk -F '\t' '
    BEGIN {
      OFS = "\t"
      print "profile_mode", "cwd", "tool", "count", "total_ms", "avg_ms", "max_ms"
    }
    NR > 1 {
      duration_ms = $3 + 0
      key = $7 SUBSEP $5 SUBSEP $2
      if (!(key in seen)) {
        seen[key] = 1
        keys[++n] = key
        profile_mode[key] = $7
        cwd[key] = $5
        tool[key] = $2
      }
      count[key] += 1
      total_ms[key] += duration_ms
      if (duration_ms > max_ms[key]) {
        max_ms[key] = duration_ms
      }
    }
    END {
      for (i = 1; i <= n; i++) {
        key = keys[i]
        avg_ms = count[key] ? total_ms[key] / count[key] : 0
        printf "%s\t%s\t%s\t%d\t%.0f\t%.1f\t%.0f\n",
          profile_mode[key], cwd[key], tool[key], count[key], total_ms[key], avg_ms, max_ms[key]
      }
    }
  ' "${timing_log}" > "${timing_dir}/tool-by-cwd.tsv"

  echo "Wrote tool timing summaries in ${timing_dir}"
}

run_profile_pytest() {
  local mode="$1"
  local filter="$2"
  local xml="$3"
  local start_utc start_ns end_utc end_ns duration_ms pytest_rc

  echo ""
  start_utc="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  start_ns="$(date +%s%N)"
  echo "--- pytest ${mode} -k ${filter} start=${start_utc} ---"
  set +e
  SVUNIT_PROFILE_MODE="${mode}" \
    SVUNIT_REUSE_BUILD="${REUSE_BUILD}" \
    SVUNIT_XSIM_REUSE_BUILD="${XSIM_REUSE_BUILD:-0}" \
    SVUNIT_SIM_DEBUG_LEVEL="${SIM_DEBUG_LEVEL:-}" \
    SVUNIT_SIM_RUNTIME_STATS="${SIM_RUNTIME_STATS:-0}" \
    SVUNIT_XSIM_RUN_MODE="${XSIM_RUN_MODE:-}" \
    python3 -m pytest -v -k "${filter}" \
    --tb=short \
    --basetemp="/artefacts/pytest-${mode}" \
    --durations=0 \
    --junitxml="${xml}" \
    2>&1
  pytest_rc=$?
  set -e
  end_utc="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  end_ns="$(date +%s%N)"
  duration_ms=$(( (end_ns - start_ns) / 1000000 ))
  echo "--- pytest ${mode} end=${end_utc} duration_ms=${duration_ms} exit_code=${pytest_rc} ---"
}

setup_tool_timing_wrappers /artefacts/tool-timing qrun vlog vopt vsim vlib vcom

# --- Version checks ---
echo "--- version checks ---"
fail=0
if [ "${TARGET_HAS_QUARTUS_SH}" = "1" ]; then
  # Capture output in a variable so a non-zero exit from the tool (which can
  # happen when the tool prints a valid header and then reports an
  # error-suppressible diagnostic, e.g. qrun 2025.1 on `-version`) does not
  # break the version check under `set -o pipefail`.
  qsh_out="$(quartus_sh --version 2>&1 || true)"
  if ! printf '%s\n' "$qsh_out" | grep -qF "${TARGET_EXPECTED_QUARTUS}"; then
    echo "FAIL: quartus_sh version does not match ${TARGET_EXPECTED_QUARTUS}" >&2
    fail=1
  else
    echo "OK: quartus_sh version matches ${TARGET_EXPECTED_QUARTUS}"
  fi
else
  echo "SKIP: quartus_sh version check (sim-only image, no Quartus installed)"
fi
for tool in qrun vlog vsim; do
  # See quartus_sh comment above; same pattern used for native Verilator at
  # lines 93-97. Shields the grep from a pipefail on a header-plus-error exit.
  tool_out="$("$tool" -version 2>&1 || true)"
  if ! printf '%s\n' "$tool_out" | grep -qF "${TARGET_EXPECTED_QUESTA}"; then
    echo "FAIL: $tool version does not match ${TARGET_EXPECTED_QUESTA}" >&2
    fail=1
  else
    echo "OK: $tool version matches ${TARGET_EXPECTED_QUESTA}"
  fi
done
if [ "$fail" -ne 0 ]; then
  echo "FAIL: version smoke checks failed" >&2
  exit 1
fi

# --- Run SVUnit test suite ---
cd /sll
source Setup.bsh
cd test
run_profile_pytest per-fixture "${PER_FIXTURE_PYTEST_FILTER}" /artefacts/tests-per-fixture.xml
run_profile_pytest compile-once "${COMPILE_ONCE_PYTEST_FILTER}" /artefacts/tests-compile-once.xml
write_tool_timing_summary /artefacts/tool-timing
CONTAINER_EOF
    )"

    # Licensing env vars: Questa 2025.1 moved from LM_LICENSE_FILE (colon-delim)
    # to SALT_LICENSE_SERVER (semicolon-delim, SALT v2.4.2.0). Older Questa
    # (2023.3 in the 23.4 image) still reads LM_LICENSE_FILE, and quartus_sh
    # on the full 23.4 image also uses LM_LICENSE_FILE. Set both so a single
    # certify.sh path works across container versions - each tool picks the
    # var it understands and ignores the other. Single license file per var,
    # so the delimiter difference doesn't matter (no separator needed).
    "${CONTAINER_RUNTIME}" run --rm \
      --net=host \
      --cap-add=NET_ADMIN \
      -e LM_LICENSE_FILE=/opt/quartus_license.dat:/opt/questa_license.dat \
      -e SALT_LICENSE_SERVER=/opt/questa_license.dat \
      -e QUARTUS_PATH="${TARGET_INSTALL_ROOT}" \
      -e QUARTUS_ROOTDIR="${TARGET_INSTALL_ROOT}/quartus" \
      -e SOPC_KIT_NIOS2="${TARGET_INSTALL_ROOT}/nios2eds" \
      -e QSYS_ROOTDIR="${TARGET_INSTALL_ROOT}/qsys/bin" \
      -e QUARTUS_64BIT=1 \
      -e LANG=C.UTF-8 \
      -e LC_ALL=C.UTF-8 \
      -e PATH="${TARGET_CONTAINER_PATH}" \
      -e TARGET_EXPECTED_QUARTUS="${TARGET_EXPECTED_QUARTUS}" \
      -e TARGET_EXPECTED_QUESTA="${TARGET_EXPECTED_QUESTA}" \
      -e TARGET_HAS_QUARTUS_SH="${TARGET_HAS_QUARTUS_SH}" \
      -e REUSE_BUILD="${REUSE_BUILD}" \
      -e XSIM_REUSE_BUILD="$([ "${TARGET_TOOL}" = "xsim" ] && echo "${REUSE_BUILD}" || echo 0)" \
      -e SIM_DEBUG_LEVEL="${SIM_DEBUG_LEVEL}" \
      -e SIM_RUNTIME_STATS="${SIM_RUNTIME_STATS}" \
      -e XSIM_RUN_MODE="${XSIM_RUN_MODE}" \
      -e PYTEST_FILTER="${PYTEST_FILTER}" \
      -e PER_FIXTURE_PYTEST_FILTER="${PER_FIXTURE_PYTEST_FILTER}" \
      -e COMPILE_ONCE_PYTEST_FILTER="${COMPILE_ONCE_PYTEST_FILTER}" \
      -v "${REPO_ROOT}:/sll" \
      -v "${LICENSE_DIR}/quartus_license.dat:/opt/quartus_license.dat:ro" \
      -v "${LICENSE_DIR}/questa_license.dat:/opt/questa_license.dat:ro" \
      -v "${OUTPUT_DIR}:/artefacts" \
      "${TARGET_IMAGE}" /bin/bash -c "$container_script" \
      > "${OUTPUT_DIR}/test-log.txt" 2>&1 || EXIT_CODE=$?
    ;;

  native)
    echo "--- Running qualification natively (${TARGET_TOOL}) ---"
    echo "--- version checks ---"
    echo "OK: verilator version = $(verilator --version 2>&1)"
    echo "OK: gcc version = $(gcc --version 2>&1 | head -1)"
    echo "OK: make version = $(make --version 2>&1 | head -1)"

    (
      cd "${REPO_ROOT}"
      # shellcheck source=/dev/null
      source Setup.bsh
      setup_tool_timing_wrappers "${OUTPUT_DIR}/tool-timing" \
        verilator gcc g++ cc c++ make ar ranlib
      cd test
      run_profile_pytest per-fixture "${PER_FIXTURE_PYTEST_FILTER}" "${OUTPUT_DIR}/tests-per-fixture.xml"
      run_profile_pytest compile-once "${COMPILE_ONCE_PYTEST_FILTER}" "${OUTPUT_DIR}/tests-compile-once.xml"
      write_tool_timing_summary "${OUTPUT_DIR}/tool-timing"
    ) > "${OUTPUT_DIR}/test-log.txt" 2>&1 || EXIT_CODE=$?
    ;;

  fhs)
    echo "--- Running qualification natively with Vivado FHS wrappers (${TARGET_TOOL}) ---"
    (
      set -euo pipefail

      echo "--- Vivado synth-sim-full smoke ---"
      echo "Profile: ${TARGET_VIVADO_PROFILE}"
      echo "Store:   ${TARGET_VIVADO_STORE_PATH}"
      echo ""

      SMOKE_DIR="${OUTPUT_DIR}/vivado-smoke"
      TOOL_TIMING_DIR="${OUTPUT_DIR}/vivado-tool-timing"
      mkdir -p "${SMOKE_DIR}/home"

      # Time every Vivado tool process the certifier starts.  The wrappers sit
      # ahead of the real FHS tools on PATH and include both buildFHSEnv
      # bubblewrap startup and the underlying Vivado command runtime.
      setup_tool_timing_wrappers "${TOOL_TIMING_DIR}" vivado xvlog xvhdl xelab xsim

      export SVUNIT_PROFILE_MODE=vivado-smoke
      export HOME="${SMOKE_DIR}/home"
      cd "${SMOKE_DIR}"

      for tool in vivado xvlog xvhdl xelab xsim; do
        tool_path="$(command -v "$tool")"
        echo "OK: $tool -> ${tool_path}"
      done

      cat > version.tcl <<'EOF'
puts "VIVADO_VERSION=[version -short]"
exit 0
EOF
      timeout 90 vivado -mode batch -source version.tcl -nolog -nojournal > vivado-version.log 2>&1
      grep -q "VIVADO_VERSION=${TARGET_EXPECTED_VIVADO}" vivado-version.log

      cat > tb.v <<'EOF'
`timescale 1ns / 1ps
module tb;
  initial begin
    $display("Hello from SVUnit certify Vivado smoke");
    $finish;
  end
endmodule
EOF

      xvlog tb.v > xvlog-smoke.log 2>&1
      xelab -top tb -snapshot tb_snap > xelab-smoke.log 2>&1
      xsim tb_snap --runall > xsim-smoke.log 2>&1
      grep -q "Hello from SVUnit certify Vivado smoke" xsim-smoke.log
      echo "OK: Vivado xvlog -> xelab -> xsim smoke passed"

      cd "${REPO_ROOT}"
      # shellcheck source=/dev/null
      source Setup.bsh
      cd test
      run_profile_pytest per-fixture "${PER_FIXTURE_PYTEST_FILTER}" "${OUTPUT_DIR}/tests-per-fixture.xml"
      run_profile_pytest compile-once "${COMPILE_ONCE_PYTEST_FILTER}" "${OUTPUT_DIR}/tests-compile-once.xml"
      write_tool_timing_summary "${TOOL_TIMING_DIR}"
    ) > "${OUTPUT_DIR}/test-log.txt" 2>&1 || EXIT_CODE=$?
    ;;
esac

write_sim_runtime_stats_summary "${OUTPUT_DIR}"

# ---------------------------------------------------------------------------
# Parse JUnit XML for pass/fail summary
# ---------------------------------------------------------------------------
parse_junit_counts() {
  local xml="$1"
  if [ ! -f "${xml}" ]; then
    echo "0 0 0 0"
    return 0
  fi

  # Single atomic XML parse (WR-02): prefer a <testsuites> wrapper's aggregate
  # attrs; fall back to summing across direct <testsuite> children.  On parse
  # failure, emit a clear diagnostic and zero the counters so STATUS=FAIL
  # distinguishes "parse failure" from "no tests ran" (python exits non-zero
  # and prints to stderr; previous behaviour silently collapsed both cases
  # into `0 passed, FAIL`).
  python3 - "${xml}" <<'PY'
import sys, xml.etree.ElementTree as ET
try:
    root = ET.parse(sys.argv[1]).getroot()
except (ET.ParseError, OSError) as e:
    print(f"certify.sh: failed to parse tests.xml: {e}", file=sys.stderr)
    sys.exit(2)

def intattr(node, name):
    try:
        return int(node.attrib.get(name, 0))
    except (TypeError, ValueError):
        return 0

# Prefer the top-level element's aggregate attrs if present; otherwise sum
# across direct <testsuite> children (handles pytest's <testsuites> wrapper
# that lacks aggregate attrs on the top element).
if "tests" in root.attrib:
    total = intattr(root, "tests")
    failures = intattr(root, "failures")
    errors = intattr(root, "errors")
    skipped = intattr(root, "skipped")
else:
    suites = root.findall("testsuite")
    total = sum(intattr(s, "tests") for s in suites)
    failures = sum(intattr(s, "failures") for s in suites)
    errors = sum(intattr(s, "errors") for s in suites)
    skipped = sum(intattr(s, "skipped") for s in suites)
print(total, failures, errors, skipped)
PY
}

PER_FIXTURE_XML="${OUTPUT_DIR}/tests-per-fixture.xml"
COMPILE_ONCE_XML="${OUTPUT_DIR}/tests-compile-once.xml"

if per_fixture_counts="$(parse_junit_counts "${PER_FIXTURE_XML}")"; then
  read -r PER_FIXTURE_TOTAL PER_FIXTURE_FAILURES PER_FIXTURE_ERRORS PER_FIXTURE_SKIPPED <<<"${per_fixture_counts}"
else
  echo "WARN: tests-per-fixture.xml parse failed; marking run as FAIL" >&2
  PER_FIXTURE_TOTAL=0; PER_FIXTURE_FAILURES=0; PER_FIXTURE_ERRORS=0; PER_FIXTURE_SKIPPED=0
fi
PER_FIXTURE_PASSED=$((PER_FIXTURE_TOTAL - PER_FIXTURE_FAILURES - PER_FIXTURE_ERRORS - PER_FIXTURE_SKIPPED))

if compile_once_counts="$(parse_junit_counts "${COMPILE_ONCE_XML}")"; then
  read -r COMPILE_ONCE_TOTAL COMPILE_ONCE_FAILURES COMPILE_ONCE_ERRORS COMPILE_ONCE_SKIPPED <<<"${compile_once_counts}"
else
  echo "WARN: tests-compile-once.xml parse failed; marking run as FAIL" >&2
  COMPILE_ONCE_TOTAL=0; COMPILE_ONCE_FAILURES=0; COMPILE_ONCE_ERRORS=0; COMPILE_ONCE_SKIPPED=0
fi
COMPILE_ONCE_PASSED=$((COMPILE_ONCE_TOTAL - COMPILE_ONCE_FAILURES - COMPILE_ONCE_ERRORS - COMPILE_ONCE_SKIPPED))

TOTAL=$((PER_FIXTURE_TOTAL + COMPILE_ONCE_TOTAL))
FAILURES=$((PER_FIXTURE_FAILURES + COMPILE_ONCE_FAILURES))
ERRORS=$((PER_FIXTURE_ERRORS + COMPILE_ONCE_ERRORS))
SKIPPED=$((PER_FIXTURE_SKIPPED + COMPILE_ONCE_SKIPPED))
PASSED=$((PER_FIXTURE_PASSED + COMPILE_ONCE_PASSED))

if [ -f "${PER_FIXTURE_XML}" ]; then
  cp "${PER_FIXTURE_XML}" "${OUTPUT_DIR}/tests.xml"
fi

if [ "${FAILURES}" -eq 0 ] && [ "${ERRORS}" -eq 0 ] &&
   [ "${PER_FIXTURE_PASSED}" -gt 0 ] && [ "${COMPILE_ONCE_PASSED}" -gt 0 ]; then
  STATUS="PASS"
else
  STATUS="FAIL"
fi

# ---------------------------------------------------------------------------
# timing-summary.json
# ---------------------------------------------------------------------------
if [ -f "${PER_FIXTURE_XML}" ]; then
  "${TIMING_SUMMARY_SCRIPT}" \
    "${PER_FIXTURE_XML}" "${TARGET_TOOL}" "$(hostname)" "${QH_RUN_ID}" \
    "${OUTPUT_DIR}/timing-summary.json"
  echo "Wrote timing-summary.json ($(jq '.tests | length' "${OUTPUT_DIR}/timing-summary.json") tests)"
fi

if [ -f "${COMPILE_ONCE_XML}" ]; then
  "${TIMING_SUMMARY_SCRIPT}" \
    "${COMPILE_ONCE_XML}" "${TARGET_TOOL}" "$(hostname)" "${QH_RUN_ID}-compile-once" \
    "${OUTPUT_DIR}/timing-summary-compile-once.json"
  echo "Wrote timing-summary-compile-once.json ($(jq '.tests | length' "${OUTPUT_DIR}/timing-summary-compile-once.json") tests)"
fi

# ---------------------------------------------------------------------------
# build-info.json
# ---------------------------------------------------------------------------
qh_build_info_json "${OUTPUT_DIR}/build-info.json" \
  "${TOOL_GROUP}" "${TOOL_VERSION}" "${QUALIFIED_VERSION}" \
  "${REPO_ROOT}" "nixos-25.05" "generic"

TMP_JSON="$(mktemp)"
REUSE_BUILD_JSON=false
XSIM_REUSE_BUILD_JSON=false
SIM_RUNTIME_STATS_JSON=false
if [ "${REUSE_BUILD}" = "1" ]; then
  REUSE_BUILD_JSON=true
  if [ "${TARGET_TOOL}" = "xsim" ]; then
    XSIM_REUSE_BUILD_JSON=true
  fi
fi
if [ "${SIM_RUNTIME_STATS}" = "1" ]; then
  SIM_RUNTIME_STATS_JSON=true
fi
JQ_COMMON=(
  --arg target "${TARGET_NAME}"
  --arg sim "${TARGET_TOOL}"
  --arg sim_display "${TARGET_DISPLAY_NAME}"
  --arg svunit_commit "${SVUNIT_COMMIT}"
  --arg pytest_filter "${PYTEST_FILTER}"
  --arg sim_debug_level "${SIM_DEBUG_LEVEL}"
  --arg xsim_run_mode "${XSIM_RUN_MODE:-separate}"
  --arg per_fixture_pytest_filter "${PER_FIXTURE_PYTEST_FILTER}"
  --arg compile_once_pytest_filter "${COMPILE_ONCE_PYTEST_FILTER}"
  --arg status "${STATUS}"
  --argjson reuse_build "${REUSE_BUILD_JSON}"
  --argjson xsim_reuse_build "${XSIM_REUSE_BUILD_JSON}"
  --argjson sim_runtime_stats "${SIM_RUNTIME_STATS_JSON}"
  --argjson tests_total "${TOTAL}"
  --argjson tests_passed "${PASSED}"
  --argjson tests_failed "${FAILURES}"
  --argjson tests_errors "${ERRORS}"
  --argjson tests_skipped "${SKIPPED}"
  --argjson per_fixture_tests_total "${PER_FIXTURE_TOTAL}"
  --argjson per_fixture_tests_passed "${PER_FIXTURE_PASSED}"
  --argjson per_fixture_tests_failed "${PER_FIXTURE_FAILURES}"
  --argjson per_fixture_tests_errors "${PER_FIXTURE_ERRORS}"
  --argjson per_fixture_tests_skipped "${PER_FIXTURE_SKIPPED}"
  --argjson compile_once_tests_total "${COMPILE_ONCE_TOTAL}"
  --argjson compile_once_tests_passed "${COMPILE_ONCE_PASSED}"
  --argjson compile_once_tests_failed "${COMPILE_ONCE_FAILURES}"
  --argjson compile_once_tests_errors "${COMPILE_ONCE_ERRORS}"
  --argjson compile_once_tests_skipped "${COMPILE_ONCE_SKIPPED}"
  --argjson exit_code "${EXIT_CODE}"
)

# Guard: every adapter must write JQ output to TMP_JSON before the mv below,
# otherwise the good JSON qh_build_info_json just wrote gets clobbered by an
# empty file.  An unhandled adapter is a programming error - abort, don't
# silently corrupt artefacts.
case "${TARGET_ADAPTER}" in
  container)
    # Sim-only images report "N/A (sim-only)" rather than an empty string
    # so downstream consumers can distinguish absent-by-design from missing-value.
    QUARTUS_VERSION_REPORTED="${TARGET_EXPECTED_QUARTUS:-N/A (sim-only)}"
    jq "${JQ_COMMON[@]}" \
      --arg image_tag "${TARGET_IMAGE}" \
      --arg image_id "${IMAGE_ID}" \
      --arg quartus_version "${QUARTUS_VERSION_REPORTED}" \
      --arg questa_version "${TARGET_EXPECTED_QUESTA}" \
      '. + {
        target: $target, simulator: $sim, simulator_display: $sim_display,
        container_image_tag: $image_tag, container_image_id: $image_id,
        quartus_version: $quartus_version, questa_version: $questa_version,
        svunit_commit: $svunit_commit, pytest_filter: $pytest_filter,
        sim_debug_level: $sim_debug_level,
        xsim_run_mode: $xsim_run_mode,
        per_fixture_pytest_filter: $per_fixture_pytest_filter,
        compile_once_pytest_filter: $compile_once_pytest_filter,
        reuse_build: $reuse_build,
        xsim_reuse_build: $xsim_reuse_build,
        sim_runtime_stats: $sim_runtime_stats,
        qualification_status: $status,
        tests_total: $tests_total, tests_passed: $tests_passed,
        tests_failed: $tests_failed, tests_errors: $tests_errors,
        tests_skipped: $tests_skipped,
        per_fixture_tests_total: $per_fixture_tests_total,
        per_fixture_tests_passed: $per_fixture_tests_passed,
        per_fixture_tests_failed: $per_fixture_tests_failed,
        per_fixture_tests_errors: $per_fixture_tests_errors,
        per_fixture_tests_skipped: $per_fixture_tests_skipped,
        compile_once_tests_total: $compile_once_tests_total,
        compile_once_tests_passed: $compile_once_tests_passed,
        compile_once_tests_failed: $compile_once_tests_failed,
        compile_once_tests_errors: $compile_once_tests_errors,
        compile_once_tests_skipped: $compile_once_tests_skipped,
        exit_code: $exit_code
      }' "${OUTPUT_DIR}/build-info.json" > "${TMP_JSON}"
    ;;
  native)
    jq "${JQ_COMMON[@]}" \
      --arg verilator_version "${TARGET_EXPECTED_VERILATOR}" \
      --arg verilator_store_path "${TARGET_VERILATOR_STORE_PATH}" \
      '. + {
        target: $target, simulator: $sim, simulator_display: $sim_display,
        verilator_version: $verilator_version,
        verilator_store_path: $verilator_store_path,
        svunit_commit: $svunit_commit, pytest_filter: $pytest_filter,
        sim_debug_level: $sim_debug_level,
        xsim_run_mode: $xsim_run_mode,
        per_fixture_pytest_filter: $per_fixture_pytest_filter,
        compile_once_pytest_filter: $compile_once_pytest_filter,
        reuse_build: $reuse_build,
        xsim_reuse_build: $xsim_reuse_build,
        sim_runtime_stats: $sim_runtime_stats,
        qualification_status: $status,
        tests_total: $tests_total, tests_passed: $tests_passed,
        tests_failed: $tests_failed, tests_errors: $tests_errors,
        tests_skipped: $tests_skipped,
        per_fixture_tests_total: $per_fixture_tests_total,
        per_fixture_tests_passed: $per_fixture_tests_passed,
        per_fixture_tests_failed: $per_fixture_tests_failed,
        per_fixture_tests_errors: $per_fixture_tests_errors,
        per_fixture_tests_skipped: $per_fixture_tests_skipped,
        compile_once_tests_total: $compile_once_tests_total,
        compile_once_tests_passed: $compile_once_tests_passed,
        compile_once_tests_failed: $compile_once_tests_failed,
        compile_once_tests_errors: $compile_once_tests_errors,
        compile_once_tests_skipped: $compile_once_tests_skipped,
        exit_code: $exit_code
      }' "${OUTPUT_DIR}/build-info.json" > "${TMP_JSON}"
    ;;
  fhs)
    VIVADO_IS_STUB_JSON=false
    if [ "${TARGET_VIVADO_IS_STUB}" = "1" ]; then
      VIVADO_IS_STUB_JSON=true
    fi
    jq "${JQ_COMMON[@]}" \
      --arg vivado_version "${TARGET_EXPECTED_VIVADO}" \
      --arg vivado_profile "${TARGET_VIVADO_PROFILE}" \
      --arg vivado_store_path "${TARGET_VIVADO_STORE_PATH}" \
      --arg vivado_qualified_root "${TARGET_QUALIFIED_ROOT}" \
      --argjson vivado_is_stub "${VIVADO_IS_STUB_JSON}" \
      '. + {
        target: $target, simulator: $sim, simulator_display: $sim_display,
        vivado_version: $vivado_version,
        vivado_profile: $vivado_profile,
        vivado_store_path: $vivado_store_path,
        vivado_qualified_root: $vivado_qualified_root,
        vivado_is_stub: $vivado_is_stub,
        svunit_commit: $svunit_commit, pytest_filter: $pytest_filter,
        sim_debug_level: $sim_debug_level,
        xsim_run_mode: $xsim_run_mode,
        per_fixture_pytest_filter: $per_fixture_pytest_filter,
        compile_once_pytest_filter: $compile_once_pytest_filter,
        reuse_build: $reuse_build,
        xsim_reuse_build: $xsim_reuse_build,
        sim_runtime_stats: $sim_runtime_stats,
        qualification_status: $status,
        tests_total: $tests_total, tests_passed: $tests_passed,
        tests_failed: $tests_failed, tests_errors: $tests_errors,
        tests_skipped: $tests_skipped,
        per_fixture_tests_total: $per_fixture_tests_total,
        per_fixture_tests_passed: $per_fixture_tests_passed,
        per_fixture_tests_failed: $per_fixture_tests_failed,
        per_fixture_tests_errors: $per_fixture_tests_errors,
        per_fixture_tests_skipped: $per_fixture_tests_skipped,
        compile_once_tests_total: $compile_once_tests_total,
        compile_once_tests_passed: $compile_once_tests_passed,
        compile_once_tests_failed: $compile_once_tests_failed,
        compile_once_tests_errors: $compile_once_tests_errors,
        compile_once_tests_skipped: $compile_once_tests_skipped,
        exit_code: $exit_code
      }' "${OUTPUT_DIR}/build-info.json" > "${TMP_JSON}"
    ;;
  *)
    echo "ERROR: build-info.json JSON stage not implemented for adapter '${TARGET_ADAPTER}'" >&2
    rm -f "${TMP_JSON}"
    exit 2
    ;;
esac
mv "${TMP_JSON}" "${OUTPUT_DIR}/build-info.json"

# ---------------------------------------------------------------------------
# qualification-results.md
# ---------------------------------------------------------------------------
OS_VER="$(grep '^VERSION_ID=' /etc/os-release 2>/dev/null | cut -d= -f2 | tr -d '"' || echo unknown)"
NIX_VER="$(nix --version 2>/dev/null | awk '{print $NF}' || echo unknown)"
KERNEL_VER="$(uname -r)"

{
  cat <<QREOF
# Qualification Results - ${TOOL_GROUP} ${TOOL_VERSION}

**Target:** ${TARGET_NAME}
**Run ID:** ${QH_RUN_ID}
**Pass:** generic
**Executed:** $(date -u +"%Y-%m-%dT%H:%M:%SZ")
**Overall:** ${STATUS} (${PASSED} passed, ${FAILURES} failed, ${SKIPPED} skipped)

## Environment

| Field | Value |
|-------|-------|
| OS | NixOS ${OS_VER} |
| Kernel | ${KERNEL_VER} |
| Nix | ${NIX_VER} |
| Platform | x86_64-linux |
| Hostname | $(hostname) |
QREOF

  case "${TARGET_ADAPTER}" in
    container)
      cat <<SIMEOF

## Simulator

| Field | Value |
|-------|-------|
| Target | ${TARGET_NAME} |
| Simulator | ${TARGET_TOOL} |
| Description | ${TARGET_DISPLAY_NAME} |
| Container Image | ${TARGET_IMAGE} |
| Container Image ID | ${IMAGE_ID} |
| Quartus Version | ${TARGET_EXPECTED_QUARTUS:-N/A (sim-only)} |
| Questa Version | ${TARGET_EXPECTED_QUESTA} |
SIMEOF
      ;;
    native)
      cat <<SIMEOF

## Simulator

| Field | Value |
|-------|-------|
| Target | ${TARGET_NAME} |
| Simulator | ${TARGET_TOOL} |
| Description | ${TARGET_DISPLAY_NAME} |
| Verilator Version | ${TARGET_EXPECTED_VERILATOR} |
| Verilator Store Path | ${TARGET_VERILATOR_STORE_PATH} |
| Container | None (native execution) |
SIMEOF
      ;;
    fhs)
      cat <<SIMEOF

## Simulator

| Field | Value |
|-------|-------|
| Target | ${TARGET_NAME} |
| Simulator | ${TARGET_TOOL} |
| Description | ${TARGET_DISPLAY_NAME} |
| Vivado Version | ${TARGET_EXPECTED_VIVADO} |
| Vivado Profile | ${TARGET_VIVADO_PROFILE} |
| Vivado Store Path | ${TARGET_VIVADO_STORE_PATH} |
| Qualified Root | ${TARGET_QUALIFIED_ROOT} |
| Container | None (native buildFHSEnv wrappers) |
SIMEOF
      ;;
    *)
      # Guard: unhandled adapter would leave the markdown without its
      # Simulator section, breaking the qualification standard's layout.
      echo "ERROR: qualification-results.md Simulator section not implemented for adapter '${TARGET_ADAPTER}'" >&2
      exit 2
      ;;
  esac

  cat <<TAILEOF

## SVUnit

| Field | Value |
|-------|-------|
| Qualified Version | ${QUALIFIED_VERSION} |
| Commit | ${SVUNIT_COMMIT} |
| Base Pytest Filter | ${PYTEST_FILTER} |
| Simulator Debug Level | ${SIM_DEBUG_LEVEL:-default} |
| xsim Run Mode | ${XSIM_RUN_MODE:-separate} |
| Per-Fixture Pytest Filter | ${PER_FIXTURE_PYTEST_FILTER} |
| Compile-Once Pytest Filter | ${COMPILE_ONCE_PYTEST_FILTER} |
| Reuse Build | ${REUSE_BUILD} |
| Simulator Runtime Stats | ${SIM_RUNTIME_STATS} |

## Test Summary

| Metric | Count |
|--------|-------|
| Total | ${TOTAL} |
| Passed | ${PASSED} |
| Failed | ${FAILURES} |
| Errors | ${ERRORS} |
| Skipped | ${SKIPPED} |

## Regression Modes

| Mode | Total | Passed | Failed | Errors | Skipped | Purpose |
|------|------:|-------:|-------:|-------:|--------:|---------|
| per-fixture | ${PER_FIXTURE_TOTAL} | ${PER_FIXTURE_PASSED} | ${PER_FIXTURE_FAILURES} | ${PER_FIXTURE_ERRORS} | ${PER_FIXTURE_SKIPPED} | Final-regression style: pytest fixture isolation, with a fresh SVUnit build/compile/run per fixture. |
| compile-once | ${COMPILE_ONCE_TOTAL} | ${COMPILE_ONCE_PASSED} | ${COMPILE_ONCE_FAILURES} | ${COMPILE_ONCE_ERRORS} | ${COMPILE_ONCE_SKIPPED} | Developer-iteration style: one SVUnit build compiles multiple suites in a single workspace and runs them together. |

## Evidence

- tests.xml - compatibility copy of the per-fixture JUnit XML results.
- tests-per-fixture.xml - JUnit XML results from the per-fixture regression.
- tests-compile-once.xml - JUnit XML results from the compile-once multi-fixture regression.
- test-log.txt - full output including version checks and both pytest outputs.
- build-info.json - machine-readable qualification metadata.
- timing-summary.json - per-fixture per-test durations for cross-simulator profiling.
- timing-summary-compile-once.json - compile-once per-test durations for cross-simulator profiling.
- sim-runtime-stats.tsv - parsed simulator runtime statistics from retained pytest run logs when enabled.
- sim-runtime-stats.json - machine-readable simulator runtime statistics summary.
- pytest-per-fixture/ and pytest-compile-once/ - retained pytest workspaces, including simulator run logs used for runtime-stat parsing.
TAILEOF

  if [ "${TARGET_ADAPTER}" = "container" ]; then
    echo "- image-inspect.json - container image metadata."
    echo "- tool-timing/tool-invocations.tsv - per-process simulator/tool timings tagged by regression mode, with start/end timestamps."
    echo "- tool-timing/tool-summary.tsv - simulator/tool timing totals by regression mode and tool."
    echo "- tool-timing/tool-by-cwd.tsv - simulator/tool timing totals by regression mode, workspace, and tool."
  fi
  if [ "${TARGET_ADAPTER}" = "native" ]; then
    echo "- tool-timing/tool-invocations.tsv - per-process Verilator/toolchain timings tagged by regression mode, with start/end timestamps."
    echo "- tool-timing/tool-summary.tsv - Verilator/toolchain timing totals by regression mode and tool."
    echo "- tool-timing/tool-by-cwd.tsv - Verilator/toolchain timing totals by regression mode, workspace, and tool."
  fi
  if [ "${TARGET_ADAPTER}" = "fhs" ]; then
    echo "- vivado-smoke/ - direct Vivado package smoke logs for vivado, xvlog, xelab, and xsim."
    echo "- vivado-tool-timing/tool-invocations.tsv - per-process Vivado tool timings tagged by regression mode, including FHS wrapper startup, with start/end timestamps."
    echo "- vivado-tool-timing/tool-summary.tsv - Vivado timing totals by regression mode and tool."
    echo "- vivado-tool-timing/tool-by-cwd.tsv - Vivado timing totals by regression mode, workspace, and tool."
  fi

  # Reference the raw log rather than inlining it.  Inlining inside a fenced
  # code block is hazardous: any pytest/tool output line containing three or
  # more consecutive backticks prematurely terminates the outer fence and
  # corrupts the evidence artefact layout (WR-01).  The file is already
  # listed in the Evidence section above, so linking is sufficient and
  # avoids doubling storage.
  cat <<'RAWEOF'

## Raw Output

See `test-log.txt` in this directory for the full unmodified output.
RAWEOF
} > "${OUTPUT_DIR}/qualification-results.md"

# ---------------------------------------------------------------------------
# Update latest symlink and print summary
# ---------------------------------------------------------------------------
qh_update_latest_symlink "${ARTEFACTS_ROOT}" "${QH_RUN_ID}"

echo ""
echo "=== Qualification Complete ==="
echo "Target:   ${TARGET_NAME}"
echo "Status:   ${STATUS}"
echo "Results:  ${PASSED} passed, ${FAILURES} failed, ${ERRORS} errors, ${SKIPPED} skipped (of ${TOTAL})"
echo "Modes:    per-fixture ${PER_FIXTURE_PASSED} passed/${PER_FIXTURE_FAILURES} failed/${PER_FIXTURE_ERRORS} errors/${PER_FIXTURE_SKIPPED} skipped; compile-once ${COMPILE_ONCE_PASSED} passed/${COMPILE_ONCE_FAILURES} failed/${COMPILE_ONCE_ERRORS} errors/${COMPILE_ONCE_SKIPPED} skipped"
echo "Run ID:   ${QH_RUN_ID}"
echo "Output:   ${OUTPUT_DIR}"

if [ "${STATUS}" = "FAIL" ]; then
  exit 1
fi
