#!/usr/bin/env bash
#
# certify.sh — shared qualification runner
#
# Invoked by per-target wrapper scripts generated by the flake.  The wrapper
# exports TARGET_* env vars describing the simulator target, then execs this
# script.  This script dispatches on $TARGET_ADAPTER to run the test suite
# and produce a standard set of qualification artefacts.
#
# Required env vars (all targets):
#   TARGET_NAME          registry key (e.g. quartus-25.1-sim-only-qrun)
#   TARGET_ADAPTER       "container" | "native" | "fhs"
#   TARGET_DISPLAY_NAME  human-readable
#   TARGET_TOOL          simulator tool name (qrun|modelsim|verilator|xsim)
#   TARGET_PYTEST_FILTER pytest -k expression
#   TOOL_GROUP, TOOL_VERSION, QUALIFIED_VERSION  qualification identifiers
#   ARTEFACTS_ROOT       parent dir to write run-id subdir into
#   CERT_TOOLS_DIR       path to qualification-helpers.sh host dir
#   TIMING_SUMMARY_SCRIPT  nix store path to timing-summary.py
#
# Container adapter extras:
#   TARGET_IMAGE, TARGET_INSTALL_ROOT, TARGET_CONTAINER_PATH,
#   TARGET_EXPECTED_QUARTUS ("" to skip), TARGET_EXPECTED_QUESTA,
#   TARGET_HAS_QUARTUS_SH (0|1), LICENSE_DIR, CONTAINER_RUNTIME
#
# Native adapter extras:
#   TARGET_EXPECTED_VERILATOR, TARGET_VERILATOR_STORE_PATH
#
# FHS adapter extras (stub): TARGET_EXPECTED_XSIM, TARGET_XSIM_STORE_PATH

set -euo pipefail

# shellcheck source=/dev/null
source "${CERT_TOOLS_DIR}/scripts/qualification-helpers.sh"

OUTPUT_DIR=""
PYTEST_FILTER_OVERRIDE=""
REPO_ROOT="${REPO_ROOT:-$(pwd)}"

usage() {
  cat <<EOF
Usage: svunit-certify-${TARGET_NAME} [--output-dir DIR] [--filter EXPR]

Target:  ${TARGET_NAME}
Adapter: ${TARGET_ADAPTER}
Display: ${TARGET_DISPLAY_NAME}

Options:
  --output-dir DIR   Override artefact output dir (default: per qualification standard)
  --filter EXPR      Override pytest -k filter (default: ${TARGET_PYTEST_FILTER})
EOF
  exit 2
}

while [ $# -gt 0 ]; do
  case "$1" in
    --output-dir|-o) OUTPUT_DIR="$2"; shift 2 ;;
    --filter|-k)     PYTEST_FILTER_OVERRIDE="$2"; shift 2 ;;
    --help|-h)       usage ;;
    *) echo "Unknown argument: $1" >&2; usage ;;
  esac
done

PYTEST_FILTER="${PYTEST_FILTER_OVERRIDE:-${TARGET_PYTEST_FILTER}}"

if [ ! -f "${REPO_ROOT}/Setup.bsh" ]; then
  echo "ERROR: Setup.bsh not found. Run from the SVUnit repo root or set REPO_ROOT." >&2
  exit 2
fi

# ---------------------------------------------------------------------------
# Adapter pre-validation (before we create any artefacts)
# ---------------------------------------------------------------------------
case "${TARGET_ADAPTER}" in
  container)
    for lic in quartus_license.dat questa_license.dat; do
      if [ ! -f "${LICENSE_DIR}/${lic}" ]; then
        echo "ERROR: Missing ${LICENSE_DIR}/${lic}" >&2
        exit 2
      fi
    done
    if ! "${CONTAINER_RUNTIME}" image exists "${TARGET_IMAGE}" >/dev/null 2>&1; then
      echo "ERROR: Container image ${TARGET_IMAGE} not found." >&2
      echo "Build it via the upstream Quartus Pro podman flake first." >&2
      exit 2
    fi
    ;;
  native)
    if ! command -v verilator >/dev/null 2>&1; then
      echo "ERROR: verilator binary not found on PATH." >&2
      exit 2
    fi
    VERILATOR_VERSION_OUT="$(verilator --version 2>&1)"
    if ! printf '%s\n' "${VERILATOR_VERSION_OUT}" | grep -qF "${TARGET_EXPECTED_VERILATOR}"; then
      echo "ERROR: verilator version mismatch — expected ${TARGET_EXPECTED_VERILATOR}, got ${VERILATOR_VERSION_OUT}" >&2
      exit 2
    fi
    for bin in gcc make; do
      if ! command -v "$bin" >/dev/null 2>&1; then
        echo "ERROR: $bin not found on PATH (required for Verilator compilation)." >&2
        exit 2
      fi
    done
    ;;
  fhs)
    echo "ERROR: FHS adapter (Vivado/xsim) is not yet implemented for ${TARGET_NAME}." >&2
    exit 2
    ;;
  *)
    echo "ERROR: Unknown adapter ${TARGET_ADAPTER} for target ${TARGET_NAME}." >&2
    exit 2
    ;;
esac

# ---------------------------------------------------------------------------
# Build run ID and prep output directory
# ---------------------------------------------------------------------------
qh_detect_gpu
qh_build_run_id --no-gpu-suffix

OUTPUT_DIR="${OUTPUT_DIR:-${ARTEFACTS_ROOT}/${QH_RUN_ID}}"
mkdir -p "${OUTPUT_DIR}"

SVUNIT_COMMIT="$(git -C "${REPO_ROOT}" rev-parse HEAD 2>/dev/null || echo "unknown")"

IMAGE_ID="N/A"
if [ "${TARGET_ADAPTER}" = "container" ]; then
  IMAGE_ID="$("${CONTAINER_RUNTIME}" image inspect "${TARGET_IMAGE}" --format '{{.Id}}' 2>/dev/null || echo "unknown")"
  "${CONTAINER_RUNTIME}" inspect "${TARGET_IMAGE}" > "${OUTPUT_DIR}/image-inspect.json" 2>/dev/null || true
fi

echo "=== SVUnit Qualification ==="
echo "Tool:       ${TOOL_GROUP} ${QUALIFIED_VERSION}"
echo "Target:     ${TARGET_NAME}"
echo "Display:    ${TARGET_DISPLAY_NAME}"
echo "Run ID:     ${QH_RUN_ID}"
echo "Output:     ${OUTPUT_DIR}"
echo "Filter:     ${PYTEST_FILTER}"
echo ""

# ---------------------------------------------------------------------------
# Run the test suite
# ---------------------------------------------------------------------------
EXIT_CODE=0

case "${TARGET_ADAPTER}" in
  container)
    echo "--- Running qualification inside container ${TARGET_IMAGE} ---"
    # shellcheck disable=SC2016
    container_script="$(cat <<'CONTAINER_EOF'
set -euo pipefail

# --- Bootstrap full Perl runtime (File::Find, IO::Dir, etc) ---
# Some sim-only container variants (e.g. quartus-pro-linux:25.1.1.125-sim-only)
# ship with `perl-base` only, which lacks core modules like File::Find (via
# perl-modules-*) and IO::Dir (via libperl5.38t64) that bin/runSVUnit and
# bin/buildSVUnit require. Installing the `perl` metapackage pulls in both.
# Idempotent — no-ops on images that already have perl full (e.g.
# quartus-pro-linux:23.4.0.79).
if ! perl -MFile::Find -MIO::Dir -e 1 >/dev/null 2>&1; then
  echo "--- bootstrap: installing perl metapackage (missing core/IO modules) ---"
  apt-get update -q >/dev/null 2>&1
  apt-get install -y -q --no-install-recommends perl >/dev/null 2>&1 \
    || { echo "FAIL: could not install perl metapackage" >&2; exit 2; }
  perl -MFile::Find -MIO::Dir -e 1 \
    || { echo "FAIL: File::Find / IO::Dir still unavailable after apt install" >&2; exit 2; }
  echo "OK: perl metapackage installed (File::Find, IO::Dir, etc available)"
fi

# --- Bootstrap pytest ---
python3 -c "
import urllib.request, tempfile, subprocess, sys
f = tempfile.NamedTemporaryFile(suffix='.py', delete=False)
urllib.request.urlretrieve('https://bootstrap.pypa.io/get-pip.py', f.name)
subprocess.check_call([sys.executable, f.name, '--break-system-packages', '-q'])
"
pip3 install --break-system-packages -q "pytest>=7,<9" "pytest-datafiles==2.0" 2>&1

# --- Version checks ---
echo "--- version checks ---"
fail=0
if [ "${TARGET_HAS_QUARTUS_SH}" = "1" ]; then
  # Capture output in a variable so a non-zero exit from the tool (which can
  # happen when the tool prints a valid header and then reports an
  # error-suppressible diagnostic, e.g. qrun 2025.1 on `-version`) does not
  # break the version check under `set -o pipefail`.
  qsh_out="$(quartus_sh --version 2>&1 || true)"
  if ! printf '%s\n' "$qsh_out" | grep -qF "${TARGET_EXPECTED_QUARTUS}"; then
    echo "FAIL: quartus_sh version does not match ${TARGET_EXPECTED_QUARTUS}" >&2
    fail=1
  else
    echo "OK: quartus_sh version matches ${TARGET_EXPECTED_QUARTUS}"
  fi
else
  echo "SKIP: quartus_sh version check (sim-only image, no Quartus installed)"
fi
for tool in qrun vlog vsim; do
  # See quartus_sh comment above; same pattern used for native Verilator at
  # lines 93-97. Shields the grep from a pipefail on a header-plus-error exit.
  tool_out="$("$tool" -version 2>&1 || true)"
  if ! printf '%s\n' "$tool_out" | grep -qF "${TARGET_EXPECTED_QUESTA}"; then
    echo "FAIL: $tool version does not match ${TARGET_EXPECTED_QUESTA}" >&2
    fail=1
  else
    echo "OK: $tool version matches ${TARGET_EXPECTED_QUESTA}"
  fi
done
if [ "$fail" -ne 0 ]; then
  echo "FAIL: version smoke checks failed" >&2
  exit 1
fi

# --- Run SVUnit test suite ---
cd /sll
source Setup.bsh
cd test
echo ""
echo "--- pytest -k ${PYTEST_FILTER} ---"
python3 -m pytest -v -k "${PYTEST_FILTER}" \
  --tb=short \
  --durations=0 \
  --junitxml=/artefacts/tests.xml \
  2>&1 || true
CONTAINER_EOF
    )"

    "${CONTAINER_RUNTIME}" run --rm \
      --net=host \
      --cap-add=NET_ADMIN \
      -e LM_LICENSE_FILE=/opt/quartus_license.dat:/opt/questa_license.dat \
      -e QUARTUS_PATH="${TARGET_INSTALL_ROOT}" \
      -e QUARTUS_ROOTDIR="${TARGET_INSTALL_ROOT}/quartus" \
      -e SOPC_KIT_NIOS2="${TARGET_INSTALL_ROOT}/nios2eds" \
      -e QSYS_ROOTDIR="${TARGET_INSTALL_ROOT}/qsys/bin" \
      -e QUARTUS_64BIT=1 \
      -e LANG=C.UTF-8 \
      -e LC_ALL=C.UTF-8 \
      -e PATH="${TARGET_CONTAINER_PATH}" \
      -e TARGET_EXPECTED_QUARTUS="${TARGET_EXPECTED_QUARTUS}" \
      -e TARGET_EXPECTED_QUESTA="${TARGET_EXPECTED_QUESTA}" \
      -e TARGET_HAS_QUARTUS_SH="${TARGET_HAS_QUARTUS_SH}" \
      -e PYTEST_FILTER="${PYTEST_FILTER}" \
      -v "${REPO_ROOT}:/sll" \
      -v "${LICENSE_DIR}/quartus_license.dat:/opt/quartus_license.dat:ro" \
      -v "${LICENSE_DIR}/questa_license.dat:/opt/questa_license.dat:ro" \
      -v "${OUTPUT_DIR}:/artefacts" \
      "${TARGET_IMAGE}" /bin/bash -c "$container_script" \
      > "${OUTPUT_DIR}/test-log.txt" 2>&1 || EXIT_CODE=$?
    ;;

  native)
    echo "--- Running qualification natively (${TARGET_TOOL}) ---"
    echo "--- version checks ---"
    echo "OK: verilator version = $(verilator --version 2>&1)"
    echo "OK: gcc version = $(gcc --version 2>&1 | head -1)"
    echo "OK: make version = $(make --version 2>&1 | head -1)"

    (
      cd "${REPO_ROOT}"
      # shellcheck source=/dev/null
      source Setup.bsh
      cd test
      echo ""
      echo "--- pytest -k ${PYTEST_FILTER} ---"
      python3 -m pytest -v -k "${PYTEST_FILTER}" \
        --tb=short \
        --durations=0 \
        --junitxml="${OUTPUT_DIR}/tests.xml" \
        2>&1 || true
    ) > "${OUTPUT_DIR}/test-log.txt" 2>&1 || EXIT_CODE=$?
    ;;
esac

# ---------------------------------------------------------------------------
# Parse JUnit XML for pass/fail summary
# ---------------------------------------------------------------------------
if [ -f "${OUTPUT_DIR}/tests.xml" ]; then
  TOTAL="$(grep -oP '\btests="\K[0-9]+' "${OUTPUT_DIR}/tests.xml" | head -1 || echo "0")"
  FAILURES="$(grep -oP '\bfailures="\K[0-9]+' "${OUTPUT_DIR}/tests.xml" | head -1 || echo "0")"
  ERRORS="$(grep -oP '\berrors="\K[0-9]+' "${OUTPUT_DIR}/tests.xml" | head -1 || echo "0")"
  SKIPPED="$(grep -oP '\bskipped="\K[0-9]+' "${OUTPUT_DIR}/tests.xml" | head -1 || echo "0")"
  PASSED=$((TOTAL - FAILURES - ERRORS - SKIPPED))
else
  TOTAL=0; FAILURES=0; ERRORS=0; SKIPPED=0; PASSED=0
fi

if [ "${FAILURES}" -eq 0 ] && [ "${ERRORS}" -eq 0 ] && [ "${PASSED}" -gt 0 ]; then
  STATUS="PASS"
else
  STATUS="FAIL"
fi

# ---------------------------------------------------------------------------
# timing-summary.json
# ---------------------------------------------------------------------------
if [ -f "${OUTPUT_DIR}/tests.xml" ]; then
  "${TIMING_SUMMARY_SCRIPT}" \
    "${OUTPUT_DIR}/tests.xml" "${TARGET_TOOL}" "$(hostname)" "${QH_RUN_ID}" \
    "${OUTPUT_DIR}/timing-summary.json"
  echo "Wrote timing-summary.json ($(jq '.tests | length' "${OUTPUT_DIR}/timing-summary.json") tests)"
fi

# ---------------------------------------------------------------------------
# build-info.json
# ---------------------------------------------------------------------------
qh_build_info_json "${OUTPUT_DIR}/build-info.json" \
  "${TOOL_GROUP}" "${TOOL_VERSION}" "${QUALIFIED_VERSION}" \
  "${REPO_ROOT}" "nixos-25.05" "generic"

TMP_JSON="$(mktemp)"
JQ_COMMON=(
  --arg target "${TARGET_NAME}"
  --arg sim "${TARGET_TOOL}"
  --arg sim_display "${TARGET_DISPLAY_NAME}"
  --arg svunit_commit "${SVUNIT_COMMIT}"
  --arg pytest_filter "${PYTEST_FILTER}"
  --arg status "${STATUS}"
  --argjson tests_total "${TOTAL}"
  --argjson tests_passed "${PASSED}"
  --argjson tests_failed "${FAILURES}"
  --argjson tests_errors "${ERRORS}"
  --argjson tests_skipped "${SKIPPED}"
  --argjson exit_code "${EXIT_CODE}"
)

# Guard: every adapter must write JQ output to TMP_JSON before the mv below,
# otherwise the good JSON qh_build_info_json just wrote gets clobbered by an
# empty file.  An unhandled adapter is a programming error — abort, don't
# silently corrupt artefacts.
case "${TARGET_ADAPTER}" in
  container)
    # Sim-only images report "N/A (sim-only)" rather than an empty string
    # so downstream consumers can distinguish absent-by-design from missing-value.
    QUARTUS_VERSION_REPORTED="${TARGET_EXPECTED_QUARTUS:-N/A (sim-only)}"
    jq "${JQ_COMMON[@]}" \
      --arg image_tag "${TARGET_IMAGE}" \
      --arg image_id "${IMAGE_ID}" \
      --arg quartus_version "${QUARTUS_VERSION_REPORTED}" \
      --arg questa_version "${TARGET_EXPECTED_QUESTA}" \
      '. + {
        target: $target, simulator: $sim, simulator_display: $sim_display,
        container_image_tag: $image_tag, container_image_id: $image_id,
        quartus_version: $quartus_version, questa_version: $questa_version,
        svunit_commit: $svunit_commit, pytest_filter: $pytest_filter,
        qualification_status: $status,
        tests_total: $tests_total, tests_passed: $tests_passed,
        tests_failed: $tests_failed, tests_errors: $tests_errors,
        tests_skipped: $tests_skipped, exit_code: $exit_code
      }' "${OUTPUT_DIR}/build-info.json" > "${TMP_JSON}"
    ;;
  native)
    jq "${JQ_COMMON[@]}" \
      --arg verilator_version "${TARGET_EXPECTED_VERILATOR}" \
      --arg verilator_store_path "${TARGET_VERILATOR_STORE_PATH}" \
      '. + {
        target: $target, simulator: $sim, simulator_display: $sim_display,
        verilator_version: $verilator_version,
        verilator_store_path: $verilator_store_path,
        svunit_commit: $svunit_commit, pytest_filter: $pytest_filter,
        qualification_status: $status,
        tests_total: $tests_total, tests_passed: $tests_passed,
        tests_failed: $tests_failed, tests_errors: $tests_errors,
        tests_skipped: $tests_skipped, exit_code: $exit_code
      }' "${OUTPUT_DIR}/build-info.json" > "${TMP_JSON}"
    ;;
  *)
    echo "ERROR: build-info.json JSON stage not implemented for adapter '${TARGET_ADAPTER}'" >&2
    rm -f "${TMP_JSON}"
    exit 2
    ;;
esac
mv "${TMP_JSON}" "${OUTPUT_DIR}/build-info.json"

# ---------------------------------------------------------------------------
# qualification-results.md
# ---------------------------------------------------------------------------
OS_VER="$(grep '^VERSION_ID=' /etc/os-release 2>/dev/null | cut -d= -f2 | tr -d '"' || echo unknown)"
NIX_VER="$(nix --version 2>/dev/null | awk '{print $NF}' || echo unknown)"
KERNEL_VER="$(uname -r)"

{
  cat <<QREOF
# Qualification Results — ${TOOL_GROUP} ${TOOL_VERSION}

**Target:** ${TARGET_NAME}
**Run ID:** ${QH_RUN_ID}
**Pass:** generic
**Executed:** $(date -u +"%Y-%m-%dT%H:%M:%SZ")
**Overall:** ${STATUS} (${PASSED} passed, ${FAILURES} failed, ${SKIPPED} skipped)

## Environment

| Field | Value |
|-------|-------|
| OS | NixOS ${OS_VER} |
| Kernel | ${KERNEL_VER} |
| Nix | ${NIX_VER} |
| Platform | x86_64-linux |
| Hostname | $(hostname) |
QREOF

  case "${TARGET_ADAPTER}" in
    container)
      cat <<SIMEOF

## Simulator

| Field | Value |
|-------|-------|
| Target | ${TARGET_NAME} |
| Simulator | ${TARGET_TOOL} |
| Description | ${TARGET_DISPLAY_NAME} |
| Container Image | ${TARGET_IMAGE} |
| Container Image ID | ${IMAGE_ID} |
| Quartus Version | ${TARGET_EXPECTED_QUARTUS:-N/A (sim-only)} |
| Questa Version | ${TARGET_EXPECTED_QUESTA} |
SIMEOF
      ;;
    native)
      cat <<SIMEOF

## Simulator

| Field | Value |
|-------|-------|
| Target | ${TARGET_NAME} |
| Simulator | ${TARGET_TOOL} |
| Description | ${TARGET_DISPLAY_NAME} |
| Verilator Version | ${TARGET_EXPECTED_VERILATOR} |
| Verilator Store Path | ${TARGET_VERILATOR_STORE_PATH} |
| Container | None (native execution) |
SIMEOF
      ;;
    *)
      # Guard: unhandled adapter would leave the markdown without its
      # Simulator section, breaking the qualification standard's layout.
      echo "ERROR: qualification-results.md Simulator section not implemented for adapter '${TARGET_ADAPTER}'" >&2
      exit 2
      ;;
  esac

  cat <<TAILEOF

## SVUnit

| Field | Value |
|-------|-------|
| Qualified Version | ${QUALIFIED_VERSION} |
| Commit | ${SVUNIT_COMMIT} |
| Pytest Filter | ${PYTEST_FILTER} |

## Test Summary

| Metric | Count |
|--------|-------|
| Total | ${TOTAL} |
| Passed | ${PASSED} |
| Failed | ${FAILURES} |
| Errors | ${ERRORS} |
| Skipped | ${SKIPPED} |

## Evidence

- tests.xml — JUnit XML results from the pytest run.
- test-log.txt — full output including version checks and pytest output.
- build-info.json — machine-readable qualification metadata.
- timing-summary.json — per-test durations for cross-simulator profiling.
TAILEOF

  if [ "${TARGET_ADAPTER}" = "container" ]; then
    echo "- image-inspect.json — container image metadata."
  fi

  cat <<RAWEOF

## Raw Output

\`\`\`text
$(cat "${OUTPUT_DIR}/test-log.txt")
\`\`\`
RAWEOF
} > "${OUTPUT_DIR}/qualification-results.md"

# ---------------------------------------------------------------------------
# Update latest symlink and print summary
# ---------------------------------------------------------------------------
qh_update_latest_symlink "${ARTEFACTS_ROOT}" "${QH_RUN_ID}"

echo ""
echo "=== Qualification Complete ==="
echo "Target:   ${TARGET_NAME}"
echo "Status:   ${STATUS}"
echo "Results:  ${PASSED} passed, ${FAILURES} failed, ${ERRORS} errors, ${SKIPPED} skipped (of ${TOTAL})"
echo "Run ID:   ${QH_RUN_ID}"
echo "Output:   ${OUTPUT_DIR}"

if [ "${STATUS}" = "FAIL" ]; then
  exit 1
fi
